require('dotenv').config({ path: '/home/ubuntu/wise-defense-saas/.env' });

const DB_URL = process.env.DATABASE_URL || 'postgresql://postgres:SuperSecurePassword123@localhost:5432/wisedefense?sslmode=disable';

module.exports = {
  apps: [
    {
      name: 'repair-agent',
      script: './dashboard/agents/repair-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', DATABASE_URL: DB_URL },
      error_file: './logs/repair-agent-error.log',
      out_file: './logs/repair-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'scheduler-agent',
      script: './dashboard/agents/scheduler-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        RESEND_API_KEY: process.env.RESEND_API_KEY || 're_test_key',
        RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL || 'noreply@wisedefense.com',
        APP_URL: process.env.APP_URL || 'https://wise2.net',
      },
      error_file: './logs/scheduler-agent-error.log',
      out_file: './logs/scheduler-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'engagement-agent',
      script: './dashboard/agents/engagement-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        RESEND_API_KEY: process.env.RESEND_API_KEY || 're_test_key',
        RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL || 'noreply@wisedefense.com',
        APP_URL: process.env.APP_URL || 'https://wise2.net',
      },
      error_file: './logs/engagement-agent-error.log',
      out_file: './logs/engagement-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'social-media-agent',
      script: './dashboard/agents/social-media-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        TWITTER_API_KEY: process.env.TWITTER_API_KEY || '',
        TWITTER_API_SECRET: process.env.TWITTER_API_SECRET || '',
        TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN || '',
        TWITTER_ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET || '',
        INSTAGRAM_ACCESS_TOKEN: process.env.INSTAGRAM_ACCESS_TOKEN || '',
        LINKEDIN_ACCESS_TOKEN: process.env.LINKEDIN_ACCESS_TOKEN || '',
        APP_URL: process.env.APP_URL || 'https://wise2.net',
      },
      error_file: './logs/social-media-agent-error.log',
      out_file: './logs/social-media-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'alert-orchestrator',
      script: './dashboard/agents/alert-orchestrator.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_WEBHOOK_URL: process.env.DISCORD_WEBHOOK_URL || '',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || '',
        TELEGRAM_CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID || '',
      },
      error_file: './logs/alert-orchestrator-error.log',
      out_file: './logs/alert-orchestrator.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'quality-scoring-agent',
      script: './dashboard/agents/quality-scoring-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
        OLLAMA_URL: process.env.OLLAMA_URL || 'http://localhost:11434',
      },
      error_file: './logs/quality-scoring-agent-error.log',
      out_file: './logs/quality-scoring-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-video-reviewer',
      script: './dashboard/agents/discord-video-reviewer.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_TOKEN: process.env.DISCORD_TOKEN || '',
        DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID || '',
      },
      error_file: './logs/discord-video-reviewer-error.log',
      out_file: './logs/discord-video-reviewer.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'youtube-uploader-agent',
      script: './dashboard/agents/youtube-uploader-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY || '',
        YOUTUBE_CHANNEL_ID: process.env.YOUTUBE_CHANNEL_ID || '',
        YOUTUBE_ACCESS_TOKEN: process.env.YOUTUBE_ACCESS_TOKEN || '',
      },
      error_file: './logs/youtube-uploader-agent-error.log',
      out_file: './logs/youtube-uploader-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-bot',
      script: './dashboard/agents/discord-bot.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_TOKEN: process.env.DISCORD_TOKEN || '',
        DISCORD_CHANNEL_ANNOUNCEMENTS: process.env.DISCORD_CHANNEL_ANNOUNCEMENTS || '',
        DISCORD_CHANNEL_TIPS: process.env.DISCORD_CHANNEL_TIPS || '',
        DISCORD_SERVER_ID: process.env.DISCORD_SERVER_ID || '',
      },
      error_file: './logs/discord-bot-error.log',
      out_file: './logs/discord-bot.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-control-bot',
      script: './dashboard/agents/discord-control-bot.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_TOKEN: process.env.DISCORD_CONTROL_BOT_TOKEN || process.env.DISCORD_TOKEN || '',
        DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID || '',
      },
      error_file: './logs/discord-control-bot-error.log',
      out_file: './logs/discord-control-bot.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'telegram-bot',
      script: './dashboard/agents/telegram-bot.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN || '',
        TELEGRAM_CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID || '',
      },
      error_file: './logs/telegram-bot-error.log',
      out_file: './logs/telegram-bot.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'youtube-agent',
      script: './dashboard/agents/youtube-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY || '',
        YOUTUBE_CHANNEL_ID: process.env.YOUTUBE_CHANNEL_ID || '',
        YOUTUBE_ACCESS_TOKEN: process.env.YOUTUBE_ACCESS_TOKEN || '',
      },
      error_file: './logs/youtube-agent-error.log',
      out_file: './logs/youtube-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'news-scraper',
      script: './dashboard/agents/news-scraper.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        NEWS_API_KEY: process.env.NEWS_API_KEY || '',
      },
      error_file: './logs/news-scraper-error.log',
      out_file: './logs/news-scraper.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'content-reviewer',
      script: './dashboard/agents/content-reviewer.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/content-reviewer-error.log',
      out_file: './logs/content-reviewer.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-alerts',
      script: './dashboard/agents/discord-alerts.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_NEWS_WEBHOOK_URL: process.env.DISCORD_NEWS_WEBHOOK_URL || '',
        DISCORD_BREAKING_NEWS_WEBHOOK_URL: process.env.DISCORD_BREAKING_NEWS_WEBHOOK_URL || '',
        DISCORD_ALERT_ROLE_ID: process.env.DISCORD_ALERT_ROLE_ID || '',
        DISCORD_BREAKING_NEWS_ROLE_ID: process.env.DISCORD_BREAKING_NEWS_ROLE_ID || '',
        DISCORD_2A_ROLE_ID: process.env.DISCORD_2A_ROLE_ID || '',
      },
      error_file: './logs/discord-alerts-error.log',
      out_file: './logs/discord-alerts.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-approval-workflow',
      script: './dashboard/agents/discord-approval-workflow.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_NEWS_WEBHOOK_URL: process.env.DISCORD_NEWS_WEBHOOK_URL || '',
        DISCORD_APPROVAL_CHANNEL_ID: process.env.DISCORD_APPROVAL_CHANNEL_ID || '',
      },
      error_file: './logs/discord-approval-workflow-error.log',
      out_file: './logs/discord-approval-workflow.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'discord-content-bot',
      script: './dashboard/agents/discord-content-bot.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        DISCORD_BOT_TOKEN: process.env.DISCORD_TOKEN || '',
        DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID || '',
        DISCORD_APPROVAL_CHANNEL_ID: process.env.DISCORD_APPROVAL_CHANNEL_ID || '',
      },
      error_file: './logs/discord-content-bot-error.log',
      out_file: './logs/discord-content-bot.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'submission-api',
      script: './dashboard/agents/submission-api.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/submission-api-error.log',
      out_file: './logs/submission-api.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'health-monitor-agent',
      script: './dashboard/agents/health-monitor-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/health-monitor-agent-error.log',
      out_file: './logs/health-monitor-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'analytics-agent',
      script: './dashboard/agents/analytics-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/analytics-agent-error.log',
      out_file: './logs/analytics-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'leaderboard-agent',
      script: './dashboard/agents/leaderboard-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/leaderboard-agent-error.log',
      out_file: './logs/leaderboard-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'failed-post-retry-agent',
      script: './dashboard/agents/failed-post-retry-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
      },
      error_file: './logs/failed-post-retry-agent-error.log',
      out_file: './logs/failed-post-retry-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      autorestart: true,
      watch: false,
    },
    {
      name: 'tiktok-agent',
      script: './dashboard/agents/tiktok-agent.js',
      cwd: '/home/ubuntu/wise-defense-saas',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: DB_URL,
        TIKTOK_ACCESS_TOKEN: process.env.TIKTOK_ACCESS_TOKEN || '',
        TIKTOK_BUSINESS_ACCOUNT_ID: process.env.TIKTOK_BUSINESS_ACCOUNT_ID || '',
      },
      error_file: './logs/tiktok-agent-error.log',
      out_file: './logs/tiktok-agent.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
    },
  ],
};
