/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router — do not edit manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const OperationsRoute = OperationsRouteImport.update({ id: '/operations', path: '/operations', getParentRoute: () => rootRouteImport } as any)
const IntelligenceRoute = IntelligenceRouteImport.update({ id: '/intelligence', path: '/intelligence', getParentRoute: () => rootRouteImport } as any)
const InfrastructureRoute = InfrastructureRouteImport.update({ id: '/infrastructure', path: '/infrastructure', getParentRoute: () => rootRouteImport } as any)
const BusinessRoute = BusinessRouteImport.update({ id: '/business', path: '/business', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/infrastructure': typeof InfrastructureRoute
  '/intelligence': typeof IntelligenceRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business' | '/infrastructure' | '/intelligence' | '/operations' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business' | '/infrastructure' | '/intelligence' | '/operations' | '/settings'
  id: '__root__' | '/' | '/business' | '/infrastructure' | '/intelligence' | '/operations' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  InfrastructureRoute: typeof InfrastructureRoute
  IntelligenceRoute: typeof IntelligenceRoute
  OperationsRoute: typeof OperationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/operations': { id: '/operations'; path: '/operations'; fullPath: '/operations'; preLoaderRoute: typeof OperationsRouteImport; parentRoute: typeof rootRouteImport }
    '/intelligence': { id: '/intelligence'; path: '/intelligence'; fullPath: '/intelligence'; preLoaderRoute: typeof IntelligenceRouteImport; parentRoute: typeof rootRouteImport }
    '/infrastructure': { id: '/infrastructure'; path: '/infrastructure'; fullPath: '/infrastructure'; preLoaderRoute: typeof InfrastructureRouteImport; parentRoute: typeof rootRouteImport }
    '/business': { id: '/business'; path: '/business'; fullPath: '/business'; preLoaderRoute: typeof BusinessRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  BusinessRoute,
  InfrastructureRoute,
  IntelligenceRoute,
  OperationsRoute,
  SettingsRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
